### ISSUE TITLE
Incorrect instructions in GitHub Actions: Continuous Delivery with Azure lab

### ISSUE THREAD

**Issue by datanerd** [githubtraining/continuous-delivery-azure#40]
**Describe the bug**
Incorrect instructions in GitHub Actions: Continuous Delivery with Azure lab

**To Reproduce**
The Step 8 in the lab requests to add the following lines to `deploy-prod.yml`:
```
env:
  AZURE_RESOURCE_GROUP: cd-with-actions
  AZURE_APP_PLAN: actions-ttt-deployment
  AZURE_LOCATION: '"Central US"'
  #################################################
  ### USER PROVIDED VALUES ARE REQUIRED BELOW   ###
  #################################################
  #################################################
  ### REPLACE USERNAME WITH GH USERNAME         ###
  AZURE_WEBAPP_NAME: andrekolodochka-ttt-app
  #################################################
```
(`andrekolodochka-ttt-app` above will be different for each user)

![image](https://user-images.githubusercontent.com/59625655/134131511-a5343f07-cd50-4064-b7f0-de0ff2d24f59.png)

Doing so will result in errors in `create image and store in Packages` step:
![image](https://user-images.githubusercontent.com/59625655/134131801-4ab3790b-c871-44e0-8d16-fd5d946c9bbc.png)

**Expected behavior**
The correct lines to add are:

```
env:
  DOCKER_IMAGE_NAME: andrekolodochka-azure-ttt
  IMAGE_REGISTRY_URL: docker.pkg.github.com
  #################################################
  ### USER PROVIDED VALUES ARE REQUIRED BELOW   ###
  #################################################
  #################################################
  ### REPLACE USERNAME WITH GH USERNAME         ###
  AZURE_WEBAPP_NAME: andrekolodochka-ttt-app
  #################################################
```
(again, `andrekolodochka` above will be different per user)

This is actually how it is shown at a later Step 9 in the same PR in the lab:
![image](https://user-images.githubusercontent.com/59625655/134132330-7f47b806-9718-4397-a889-da109b4e4317.png)

So if I copy and replace the whole workflow in Step 9 - it would work. But if I only copy-paste the `jobs` section - I'd get an error in `create image and store in Packages` step.
